spring:
  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:tcp://localhost/~/haru
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
      show_sql: true
      format_sql: true
    open-in-view: false
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

logging.level:
  org.hibernate.SQL: debug

jwt:
  headers: Authorization
  secret: YWxzZGtqYmwtc2Rma2VtbXhjLWZkYWdkc2EtZHVtZW1hc2lsLWRrbHRqa2xzZmprbHNpZWxhCgfdll34fjbnjF452DFawd123F234
  refresh-secret: ZGZqbDJpdmtqZmlobHNsLWZqaWRlamRsYWZzaWVqZy1mZWZzZGZuamtibGRmamtzZWwtYmppa2xkamZpbGVzbmxqbGJrbHNlLWZlZmpqaTEyMzU0MDIzLXNhamtsZmplbAo
  token-validity-in-seconds: 10
  refresh-validity-in-seconds: 86400